/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx,js,jsx}'],
  theme: {
    extend: {
      colors: {
        // Shared government CSS-variable tokens
        canvas: 'var(--color-canvas, #f8fafc)',
        surface: {
          DEFAULT: 'var(--color-surface, #ffffff)',
          2: 'var(--color-surface-2, #f1f5f9)',
          3: 'var(--color-surface-3, #e2e8f0)',
        },
        border: 'var(--color-border, #e2e8f0)',
        'border-strong': 'var(--color-border-strong, #cbd5e1)',
        hover: 'var(--color-hover, #f1f5f9)',
        fg: {
          DEFAULT: 'var(--color-fg, #0f172a)',
          muted: 'var(--color-fg-muted, #475569)',
          subtle: 'var(--color-fg-subtle, #64748b)',
          inverted: 'var(--color-fg-inverted, #ffffff)',
        },
        primary: {
          DEFAULT: 'var(--color-primary, #1e40af)',
          strong: 'var(--color-primary-strong, #1d4ed8)',
          soft: 'var(--color-primary-soft, #eff6ff)',
          border: 'var(--color-primary-border, #bfdbfe)',
          on: 'var(--color-on-primary, #ffffff)',
        },
        secondary: {
          DEFAULT: 'var(--color-secondary, #12395d)',
          soft: 'var(--color-secondary-soft, #eff4ff)',
          fg: 'var(--color-secondary-fg, #ffffff)',
        },
        success: {
          DEFAULT: 'var(--color-success, #15803d)',
          strong: 'var(--color-success-strong, #16a34a)',
          tint: 'var(--color-success-tint, #f0fdf4)',
          border: 'var(--color-success-border, #bbf7d0)',
        },
        warning: {
          DEFAULT: 'var(--color-warning, #b45309)',
          strong: 'var(--color-warning-strong, #d97706)',
          tint: 'var(--color-warning-tint, #fffbeb)',
          border: 'var(--color-warning-border, #fde68a)',
        },
        danger: {
          DEFAULT: 'var(--color-danger, #b91c1c)',
          strong: 'var(--color-danger-strong, #dc2626)',
          tint: 'var(--color-danger-tint, #fef2f2)',
          border: 'var(--color-danger-border, #fecaca)',
        },
        info: {
          DEFAULT: 'var(--color-info, #1e40af)',
          strong: 'var(--color-info-strong, #1d4ed8)',
          tint: 'var(--color-info-tint, #eff6ff)',
          border: 'var(--color-info-border, #bfdbfe)',
        },
        saffron: 'var(--color-saffron, #ff9933)',
        'india-green': 'var(--color-india-green, #138808)',

        // Citizen portal specific container tokens
        background: '#F5F7FA',
        'on-background': '#0d1c2e',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#F1F5F9',
        'surface-container': '#E8EDF4',
        'surface-container-high': '#DDE5EF',
        'surface-container-highest': '#D2DCE9',
        'surface-bright': '#F8FAFC',
        'surface-dim': '#CBD5E1',
        'surface-variant': '#D5DFEC',
        'on-surface': '#0d1c2e',
        'on-surface-variant': '#44474e',
        'inverse-surface': '#233144',
        'inverse-on-surface': '#eaf1ff',
        outline: '#74777f',
        'outline-variant': '#D9DEE7',
        'primary-container': '#102A4C',
        'on-primary-container': '#7a91b7',
        'primary-fixed': '#d5e3ff',
        'primary-fixed-dim': '#b0c8f1',
        'on-primary-fixed': '#001b3b',
        'secondary-container': '#fe932c',
        'on-secondary-container': '#8F4A00',
        'secondary-fixed': '#ffdcc3',
        'secondary-fixed-dim': '#ffb77d',
        tertiary: '#0B2342',
        'tertiary-container': '#17365D',
        'tertiary-fixed': '#dde1ff',
        error: '#C62828',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#8C1616',
        'success-container': '#DCFCE7',
        'info-container': '#DBEAFE',
        'warning-container': '#FEF3C7',
      },
      fontFamily: {
        sans: ['Noto Sans', 'Inter', 'Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        display: ['Cabinet Grotesk', 'Outfit', 'sans-serif'],
        mono: ['JetBrains Mono', 'Cascadia Mono', 'Consolas', 'monospace'],
      },
      fontSize: {
        // Government text hierarchy
        display: ['1.75rem', { lineHeight: '2.25rem', fontWeight: '700' }],
        'heading-1': ['1.5rem', { lineHeight: '2rem', fontWeight: '700' }],
        'heading-2': ['1.25rem', { lineHeight: '1.75rem', fontWeight: '600' }],
        'heading-3': ['1rem', { lineHeight: '1.5rem', fontWeight: '600' }],
        'body-lg': ['1rem', { lineHeight: '1.6rem' }],
        body: ['0.875rem', { lineHeight: '1.25rem' }],
        'body-small': ['0.8125rem', { lineHeight: '1.125rem' }],
        caption: ['0.75rem', { lineHeight: '1rem', fontWeight: '600' }],
        label: ['0.875rem', { lineHeight: '1.25rem', fontWeight: '600' }],
        button: ['0.875rem', { lineHeight: '1.25rem', fontWeight: '600' }],

        // Citizen text hierarchy
        'headline-sm': ['18px', { lineHeight: '26px', fontWeight: '600' }],
        'headline-md': ['22px', { lineHeight: '30px', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'display-hero': ['40px', { lineHeight: '52px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['30px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'label-md': ['13px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.03em', fontWeight: '600' }],
      },
      spacing: {
        header: 'var(--header-height, 56px)',
        'header-total': 'var(--header-total, 104px)',
        sidebar: 'var(--sidebar-width, 260px)',
        'sidebar-collapsed': 'var(--sidebar-width-collapsed, 64px)',
      },
      maxWidth: {
        content: 'var(--max-width-content, 1440px)',
      },
      borderRadius: {
        control: 'var(--radius-control, 6px)',
        badge: 'var(--radius-badge, 9999px)',
        card: 'var(--radius-card, 10px)',
        panel: 'var(--radius-panel, 12px)',
      },
      boxShadow: {
        card: 'var(--shadow-card, 0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px -1px rgba(0, 0, 0, 0.1))',
        raised: 'var(--shadow-raised, 0 4px 6px -1px rgba(0, 0, 0, 0.1))',
        modal: 'var(--shadow-modal, 0 20px 25px -5px rgba(0, 0, 0, 0.1))',
        pop: '0 8px 24px -4px rgba(15, 41, 74, 0.16), 0 4px 10px -2px rgba(15, 41, 74, 0.08)',
      },
      zIndex: {
        base: 'var(--z-base, 0)',
        sticky: 'var(--z-sticky, 20)',
        sidebar: 'var(--z-sidebar, 25)',
        header: 'var(--z-header, 30)',
        drawer: 'var(--z-drawer, 40)',
        modal: 'var(--z-modal, 50)',
        toast: 'var(--z-toast, 60)',
        skip: 'var(--z-skip, 100)',
      },
      transitionDuration: {
        fast: 'var(--duration-fast, 120ms)',
        base: 'var(--duration-base, 200ms)',
        slow: 'var(--duration-slow, 320ms)',
      },
    },
  },
  plugins: [],
};
