import type { Contractor, Tender, Grievance, FundFlow, AuditFinding, DocumentItem, LitigationCase, WorkOrder, InspectionRecord, AiInsight, CitizenProjectSummary, Officer, BillItem } from '@/types'
import { PROJECTS } from './projects'

/**
 * Demo module datasets (mock data) — one array per domain so the mock API
 * layer and pages have a single source. All names/figures are realistic
 * demonstration values, not live records.
 */

/* ---------- Officers / session (demo) ---------- */
export const DEMO_OFFICER: Officer = {
  id: 'officer-verma-rk',
  name: 'Shri R. K. Verma, IAS',
  designation: 'Chief Engineer & Project Director',
  department: 'Public Works Department',
  employeeNo: 'PWD-EMP-10427',
  roles: ['dashboard.view', 'projects.approve', 'finance.release', 'approvals.action', 'settings.manage'],
}

/* ---------- Contractors ---------- */
export const CONTRACTORS: Contractor[] = [
  {
    id: 'CTR-0001',
    name: 'ABC Infrastructure Pvt. Ltd.',
    registrationNo: 'MH/PWD/CA/2011/2210',
    class: 'Class A',
    empanelledSince: '2011-04-12',
    districts: ['Pune', 'Satara', 'Sangli', 'Amravati'],
    activeProjects: 4,
    completedProjects: 31,
    totalValueCr: 812.4,
    aiScore: 87,
    scoreBand: 'excellent',
    onTimeCompletionPct: 91,
    qualityRating: 4.4,
    pendingDefects: 2,
    litigationCount: 1,
    strengths: ['Consistent M35 QC pass rate (96%)', 'Strong plant availability across regions', 'Zero safety fatalities in 5 years'],
    risks: ['One arbitration case (₹ 2.4 Cr claim)', 'Sub-crew turnover on night shifts'],
  },
  {
    id: 'CTR-0002',
    name: 'Shivaay Watertech Ltd.',
    registrationNo: 'MH/WRD/CA/2014/1877',
    class: 'Class A',
    empanelledSince: '2014-07-03',
    districts: ['Solapur', 'Nanded', 'Latur'],
    activeProjects: 3,
    completedProjects: 17,
    totalValueCr: 486.2,
    aiScore: 71,
    scoreBand: 'good',
    onTimeCompletionPct: 74,
    qualityRating: 3.8,
    pendingDefects: 4,
    litigationCount: 2,
    strengths: ['Specialist in pump-house electromechanical works', 'Strong O&M documentation'],
    risks: ['OEM supply-chain slippages (pumping machinery)', 'Milestone slippage on 2 WRD packages'],
  },
  {
    id: 'CTR-0003',
    name: 'Apex Constr. Consortium',
    registrationNo: 'MH/UDD/CA/2016/1120',
    class: 'Class B',
    empanelledSince: '2016-11-19',
    districts: ['Nashik', 'Thane', 'Mumbai Suburban'],
    activeProjects: 2,
    completedProjects: 9,
    totalValueCr: 214.7,
    aiScore: 78,
    scoreBand: 'good',
    onTimeCompletionPct: 83,
    qualityRating: 4.1,
    pendingDefects: 1,
    litigationCount: 0,
    strengths: ['IT/ICCC delivery experience', 'Vendor SLA compliance 94%'],
    risks: ['Dependence on single fibre vendor', 'Limited road-works bench strength'],
  },
  {
    id: 'CTR-0004',
    name: 'Kalyani Buildcon',
    registrationNo: 'MH/PWD/CA/2009/0842',
    class: 'Class A',
    empanelledSince: '2009-02-27',
    districts: ['Wardha', 'Nagpur', 'Chandrapur'],
    activeProjects: 2,
    completedProjects: 22,
    totalValueCr: 364.9,
    aiScore: 64,
    scoreBand: 'average',
    onTimeCompletionPct: 68,
    qualityRating: 3.5,
    pendingDefects: 6,
    litigationCount: 1,
    strengths: ['Bridge/girder expertise in Vidarbha', 'Own batching plants at 3 districts'],
    risks: ['Foundation milestone slippage (41 days)', 'Defect liability backlog on SH-248 approach'],
  },
  {
    id: 'CTR-0005',
    name: 'M/s Sahyadri Infra',
    registrationNo: 'MH/PHED/CA/2018/0433',
    class: 'Class B',
    empanelledSince: '2018-06-11',
    districts: ['Yavatmal', 'Amravati', 'Akola'],
    activeProjects: 1,
    completedProjects: 11,
    totalValueCr: 128.3,
    aiScore: 82,
    scoreBand: 'good',
    onTimeCompletionPct: 86,
    qualityRating: 4.0,
    pendingDefects: 1,
    litigationCount: 0,
    strengths: ['JJM cluster delivery track record', 'Community coordination during pipe-laying'],
    risks: ['Thin margin — watch cash flow on future bids'],
  },
]

/* ---------- Approvals (audit trail on every action per spec) ---------- */
/* Defined in ./approvals — kept as a separate light module for nav lookups. */
export { APPROVALS } from './approvals'

/* ---------- Tenders ---------- */
export const TENDERS: Tender[] = [
  {
    id: 'eNIT/PWD/2026/0118',
    title: 'Construction of District Records Building, Chhatrapati Sambhajinagar',
    department: 'Public Works Department',
    district: 'Aurangabad',
    status: 'under_evaluation',
    estimatedCostCr: 42.6,
    publishedOn: '2026-01-10',
    submissionDeadline: '2026-02-06',
    openingDate: '2026-02-09',
    bidsReceived: 6,
    category: 'Buildings',
    mode: 'e-Tender',
    lots: [
      { bidder: 'Kalyani Buildcon', quotedAmountCr: 41.2, technicalScore: 88, financialScore: 92, bidValidityDays: 90, bidStatus: 'under_review' },
      { bidder: 'M/s Sahyadri Infra', quotedAmountCr: 42.05, technicalScore: 81, financialScore: 90, bidValidityDays: 90, bidStatus: 'under_review' },
      { bidder: 'ABC Infrastructure Pvt. Ltd.', quotedAmountCr: 43.4, technicalScore: 90, financialScore: 86, bidValidityDays: 90, bidStatus: 'accepted' },
      { bidder: 'Sanmati Engineers & Builders', quotedAmountCr: 44.1, technicalScore: 74, financialScore: 84, bidValidityDays: 90, bidStatus: 'rejected' },
    ],
  },
  {
    id: 'eNIT/WRD/2026/0093',
    title: 'Annual O&M of Lift Irrigation Pumps — Bhima Basin Phase I',
    department: 'Water Resources Department',
    district: 'Solapur',
    status: 'published',
    estimatedCostCr: 18.4,
    publishedOn: '2026-02-01',
    submissionDeadline: '2026-02-22',
    openingDate: '2026-02-25',
    bidsReceived: 0,
    category: 'Irrigation',
    mode: 'e-Tender',
    projectId: 'NIR-WRD-2026-0089',
  },
  {
    id: 'eNIT/UDD/2026/0027',
    title: 'Nashik ICCC — City Surveillance Hardware Supply & Integration',
    department: 'Urban Development Department',
    district: 'Nashik',
    status: 'awarded',
    estimatedCostCr: 36.0,
    publishedOn: '2025-11-05',
    submissionDeadline: '2025-11-28',
    openingDate: '2025-12-02',
    bidsReceived: 4,
    category: 'Urban Infrastructure',
    mode: 'Global',
    awardedTo: 'Apex Constr. Consortium',
    awardedAmountCr: 34.85,
    projectId: 'NIR-UID-2026-0311',
  },
  {
    id: 'eNIT/PHED/2026/0051',
    title: 'Intra-Village Pipe Distribution — Yavatmal Cluster 6 (JJM)',
    department: 'Public Health Engineering Department',
    district: 'Yavatmal',
    status: 'bid_open',
    estimatedCostCr: 24.8,
    publishedOn: '2026-01-20',
    submissionDeadline: '2026-02-18',
    openingDate: '2026-02-19',
    bidsReceived: 2,
    category: 'Water Supply',
    mode: 'e-Tender',
    projectId: 'NIR-PHED-2026-0117',
  },
  {
    id: 'NIT/PWD/2025/0407',
    title: 'Repairs to Divisional Circuit Houses — Nagpur Region',
    department: 'Public Works Department',
    district: 'Nagpur',
    status: 'cancelled',
    estimatedCostCr: 6.2,
    publishedOn: '2025-12-15',
    submissionDeadline: '2026-01-10',
    openingDate: '2026-01-13',
    bidsReceived: 1,
    category: 'Buildings',
    mode: 'Manually',
  },
]

/* ---------- Grievances (masked submitter per privacy rule) ---------- */
export const GRIEVANCES: Grievance[] = [
  {
    id: 'GRV-MH-9942',
    subject: 'Water logging near Jalna road work site',
    category: 'Construction Nuisance',
    projectId: 'NIR-PWD-2026-0142',
    district: 'Pune',
    status: 'in_review',
    submittedOn: '2026-02-05',
    submittedBy: 'R****l S***a (masked)',
    slaDeadline: '2026-02-12',
    assignedTo: 'Er. S. D. Kulkarni',
    priority: 'high',
    description:
      'Storm water accumulation at the diversion stretch near Ch: 43+900 after recent rains; two-wheelers skidding in evenings.',
    timeline: [
      { timestamp: '2026-02-05T09:12:00+05:30', actor: 'Citizen portal', action: 'Submitted', note: 'With 2 site photographs.' },
      { timestamp: '2026-02-05T16:40:00+05:30', actor: 'Grievance Cell, PWD Pune', action: 'Acknowledged', note: 'Assigned to Dy. Engineer (Maintenance).' },
      { timestamp: '2026-02-07T11:05:00+05:30', actor: 'Er. A. S. Shaikh', action: 'Field Visit', note: 'Verified ponding; temporary silt bags placed.' },
    ],
    attachments: 2,
  },
  {
    id: 'GRV-MH-9918',
    subject: 'Dust pollution during earthwork',
    category: 'Environment',
    projectId: 'NIR-PWD-2026-0142',
    district: 'Pune',
    status: 'action_taken',
    submittedOn: '2026-02-01',
    submittedBy: 'S****a D***e (masked)',
    slaDeadline: '2026-02-08',
    assignedTo: 'Er. V. B. Wagh',
    priority: 'medium',
    description: 'Excessive dust at haul road near village PHATAK; request water sprinkling twice daily.',
    timeline: [
      { timestamp: '2026-02-01T10:30:00+05:30', actor: 'Citizen portal', action: 'Submitted', note: '—' },
      { timestamp: '2026-02-02T09:15:00+05:30', actor: 'Grievance Cell', action: 'Acknowledged', note: 'Forwarded to contractor under air-quality conditions.' },
      { timestamp: '2026-02-04T15:20:00+05:30', actor: 'ABC Infrastructure Pvt. Ltd.', action: 'Action Taken', note: 'Second water tanker deployed; sprinkling log started.' },
    ],
    attachments: 1,
  },
  {
    id: 'GRV-MH-9871',
    subject: 'Low water pressure after new connection',
    category: 'Water Supply',
    projectId: 'NIR-PHED-2026-0117',
    district: 'Yavatmal',
    status: 'resolved',
    submittedOn: '2026-01-24',
    submittedBy: 'V*******o G***h (masked)',
    slaDeadline: '2026-01-31',
    assignedTo: 'Er. H. T. More',
    priority: 'low',
    description: 'Tap pressure dropped after cluster connection at Ward no. 7, Pusad road.',
    timeline: [
      { timestamp: '2026-01-24T08:45:00+05:30', actor: 'Citizen portal', action: 'Submitted', note: '—' },
      { timestamp: '2026-01-25T10:10:00+05:30', actor: 'PHED Yavatmal', action: 'Acknowledged', note: 'Valve position checked.' },
      { timestamp: '2026-01-27T14:00:00+05:30', actor: 'Er. H. T. More', action: 'Resolved', note: 'Air valve corrected; pressure normalized. Photo evidence on record.' },
    ],
    attachments: 0,
    resolutionNote: 'Air-lock in distribution line removed; pressure verified at 1.4 bar.',
  },
  {
    id: 'GRV-MH-9956',
    subject: 'Unauthorized excavation near school approach',
    category: 'Safety',
    district: 'Nagpur',
    status: 'submitted',
    submittedOn: '2026-02-09',
    submittedBy: 'A***h K***r (masked)',
    slaDeadline: '2026-02-16',
    assignedTo: 'Unassigned',
    priority: 'urgent',
    description: 'Trench left open near Zilla Parishad school approach road without barricading.',
    timeline: [{ timestamp: '2026-02-09T13:22:00+05:30', actor: 'Citizen portal', action: 'Submitted', note: '1 photograph attached.' }],
    attachments: 1,
  },
]

/* ---------- Bills & payments (per project; duplicate/abnormal flags are AI-assisted) ---------- */
export const BILLS: BillItem[] = [
  { id: 'BILL-2026-0311', projectId: 'NIR-PWD-2026-0142', contractor: 'ABC Infrastructure Pvt. Ltd.', billNo: 'ABC/C4/RA-11', type: 'RA Bill', amountCr: 3.84, submittedOn: '2026-01-28', mbEntry: 'MB-PUN-C4-2025-118 / 196–203', status: 'paid', verifiedBy: 'Er. S. D. Kulkarni', approvedBy: 'SE, Pune Circle', paidOn: '2026-02-06' },
  { id: 'BILL-2026-0328', projectId: 'NIR-PWD-2026-0142', contractor: 'ABC Infrastructure Pvt. Ltd.', billNo: 'ABC/C4/RA-12', type: 'RA Bill', amountCr: 4.12, submittedOn: '2026-02-04', mbEntry: 'MB-PUN-C4-2025-118 / 204–212', status: 'verified', verifiedBy: 'Er. S. D. Kulkarni' },
  { id: 'BILL-2026-0339', projectId: 'NIR-PWD-2026-0142', contractor: 'ABC Infrastructure Pvt. Ltd.', billNo: 'ABC/C4/MAT-03', type: 'Material Bill', amountCr: 1.26, submittedOn: '2026-02-08', mbEntry: 'MB-PUN-C4-2025-118 / 213', status: 'submitted' },
  { id: 'BILL-2026-0341', projectId: 'NIR-PWD-2026-0142', contractor: 'ABC Infrastructure Pvt. Ltd.', billNo: 'ABC/C4/LAB-07', type: 'Labour Bill', amountCr: 0.42, submittedOn: '2026-02-09', mbEntry: 'Wage register W-2026-02', status: 'verified', verifiedBy: 'Dy. Engineer (Maintenance)' },
  { id: 'BILL-2026-0342', projectId: 'NIR-PWD-2026-0142', contractor: 'ABC Infrastructure Pvt. Ltd.', billNo: 'ABC/C4/RA-11-DUP', type: 'RA Bill', amountCr: 3.84, submittedOn: '2026-02-09', mbEntry: 'MB-PUN-C4-2025-118 / 196–203', status: 'returned', flag: 'duplicate', flagNote: 'Matches BILL-2026-0311 (same e-MB entries, same amount). Returned to contractor; reconsideration window open.' },
  { id: 'BILL-2026-0344', projectId: 'NIR-WRD-2026-0089', contractor: 'Shivaay Watertech Ltd.', billNo: 'SWT/LI2/RA-18', type: 'RA Bill', amountCr: 22.6, submittedOn: '2026-02-02', mbEntry: 'MB-SOL-LI2-2025-042 / 88–96', status: 'approved', verifiedBy: 'Er. M. P. Joshi', approvedBy: 'Chief Engineer, WRD' },
  { id: 'BILL-2026-0351', projectId: 'NIR-WRD-2026-0089', contractor: 'Shivaay Watertech Ltd.', billNo: 'SWT/LI2/MAT-09', type: 'Material Bill', amountCr: 14.85, submittedOn: '2026-02-07', mbEntry: 'MB-SOL-LI2-2025-042 / 97', status: 'verified', verifiedBy: 'Er. M. P. Joshi', flag: 'abnormal', flagNote: 'Unit rate for pump spares 34% above SSR 2025-26 schedule. Verification with rate analysis requested before approval.' },
  { id: 'BILL-2026-0355', projectId: 'NIR-WRD-2026-0089', contractor: 'Shivaay Watertech Ltd.', billNo: 'SWT/LI2/LAB-12', type: 'Labour Bill', amountCr: 1.94, submittedOn: '2026-02-09', mbEntry: 'Wage register W-2026-02 (Solapur)', status: 'submitted' },
  { id: 'BILL-2026-0347', projectId: 'NIR-UID-2026-0311', contractor: 'Apex Constr. Consortium', billNo: 'ACC/ICCC/RA-06', type: 'RA Bill', amountCr: 9.7, submittedOn: '2026-02-05', mbEntry: 'MB-NSK-ICCC-2025-011 / 41–48', status: 'paid', verifiedBy: 'Er. A. R. Bhosale', approvedBy: 'Secretary, UDD', paidOn: '2026-02-09' },
  { id: 'BILL-2026-0352', projectId: 'NIR-UID-2026-0311', contractor: 'Apex Constr. Consortium', billNo: 'ACC/ICCC/RA-07', type: 'RA Bill', amountCr: 8.35, submittedOn: '2026-02-09', mbEntry: 'MB-NSK-ICCC-2025-011 / 49–55', status: 'submitted' },
  { id: 'BILL-2026-0349', projectId: 'NIR-PHED-2026-0117', contractor: 'M/s Sahyadri Infra', billNo: 'SI/YAV/RA-14', type: 'RA Bill', amountCr: 5.18, submittedOn: '2026-02-03', mbEntry: 'MB-YAV-JJM-2025-021 / 120–128', status: 'paid', verifiedBy: 'Er. H. T. More', approvedBy: 'SE, Amravati Circle', paidOn: '2026-02-08' },
  { id: 'BILL-2026-0353', projectId: 'NIR-PHED-2026-0117', contractor: 'M/s Sahyadri Infra', billNo: 'SI/YAV/LAB-05', type: 'Labour Bill', amountCr: 0.68, submittedOn: '2026-02-08', mbEntry: 'Wage register W-2026-02 (Yavatmal)', status: 'approved', verifiedBy: 'Er. H. T. More', approvedBy: 'EE, PHED Yavatmal' },
]

/* ---------- Fund flow (Budget & Disbursals) ---------- */
export const FUND_FLOWS: FundFlow[] = [
  { id: 'FF-2026-001', fy: '2025-2026', demandNo: 4, head: '2041 — Capital Outlay on Roads & Bridges', budgetEstimateCr: 1240.0, revisedEstimateCr: 1180.0, allocationCr: 960.0, releasedCr: 812.4, utilizedCr: 744.1, status: 'released' },
  { id: 'FF-2026-002', fy: '2025-2026', demandNo: 21, head: '4701 — Capital Outlay on Water Resources', budgetEstimateCr: 2100.0, revisedEstimateCr: 1980.0, allocationCr: 1500.0, releasedCr: 1214.0, utilizedCr: 1102.6, status: 'released' },
  { id: 'FF-2026-003', fy: '2025-2026', demandNo: 32, head: '2215 — Water Supply & Sanitation (JJM share)', budgetEstimateCr: 860.0, revisedEstimateCr: 910.0, allocationCr: 780.0, releasedCr: 655.0, utilizedCr: 588.3, status: 'released' },
  { id: 'FF-2026-004', fy: '2025-2026', demandNo: 41, head: '2217 — Urban Development (AMRUT 2.0)', budgetEstimateCr: 640.0, revisedEstimateCr: 640.0, allocationCr: 420.0, releasedCr: 298.5, utilizedCr: 251.8, status: 'allocated' },
  { id: 'FF-2026-005', fy: '2025-2026', demandNo: 47, head: '2801 — Power (Transmission augmentation)', budgetEstimateCr: 380.0, revisedEstimateCr: 355.0, allocationCr: 210.0, releasedCr: 96.2, utilizedCr: 84.0, status: 'pending' },
]

/* ---------- Audit findings ---------- */
export const AUDIT_FINDINGS: AuditFinding[] = [
  {
    id: 'AUD-2026-007',
    auditTitle: 'Local Fund Audit — PWD Pune Division (FY 2025-26 H1)',
    projectId: 'NIR-PWD-2026-0142',
    severity: 'high',
    category: 'Financial',
    observation: 'Advance to supplier (₹ 1.42 Cr) without adjustment entry for 62 days; interest exposure under clause 214, MPWD Code.',
    raisedOn: '2026-01-20',
    status: 'corrective_action',
    accountableOfficer: 'Er. S. D. Kulkarni',
    dueDate: '2026-02-28',
    irregularityAmountCr: 1.42,
  },
  {
    id: 'AUD-2026-011',
    auditTitle: 'Performance Audit — WRD Lift Schemes',
    projectId: 'NIR-WRD-2026-0089',
    severity: 'medium',
    category: 'Procurement',
    observation: 'Single tender acceptance for OEM spares without 3-quote comparison; clarification on record.',
    raisedOn: '2026-01-28',
    status: 'response_received',
    accountableOfficer: 'Er. M. P. Joshi',
    dueDate: '2026-03-10',
  },
  {
    id: 'AUD-2026-013',
    auditTitle: 'Field Inspection Coterie Audit — Nashik ICCC',
    projectId: 'NIR-UID-2026-0311',
    severity: 'low',
    category: 'Documentation',
    observation: 'Geo-tagged photos missing for 2 weekly progress claims; since regularized.',
    raisedOn: '2026-02-03',
    status: 'closed',
    accountableOfficer: 'Er. A. R. Bhosale',
    dueDate: '2026-02-15',
  },
  {
    id: 'AUD-2026-014',
    auditTitle: 'Test Check — SH-248 Bridge Site Measurement',
    projectId: 'NIR-PWD-2026-0205',
    severity: 'critical',
    category: 'Measurement',
    observation: 'Pile-length entries in e-MB exceed bore-log record by avg 1.8 m on spans 3–4; third-party verification ordered.',
    raisedOn: '2026-02-08',
    status: 'open',
    accountableOfficer: 'Er. V. B. Wagh',
    dueDate: '2026-02-20',
    irregularityAmountCr: 0.86,
  },
]

/* ---------- Documents ---------- */
export const DOCUMENTS: DocumentItem[] = [
  { id: 'DOC-100241', name: 'Administrative Approval — NIR-PWD-2026-0142 (Corrigendum-1)', category: 'Administrative Approval', projectId: 'NIR-PWD-2026-0142', uploadedOn: '2025-08-22', uploadedBy: 'EE Office, Pune (Rural)', fileSizeKb: 1842, version: 2, accessLevel: 'Internal', signedBy: 'Shri R. K. Verma, IAS' },
  { id: 'DOC-100242', name: 'Technical Sanction (Amended) — Package C-4', category: 'Technical Approval', projectId: 'NIR-PWD-2026-0142', uploadedOn: '2026-02-03', uploadedBy: 'SE Circle, Pune', fileSizeKb: 2410, version: 3, accessLevel: 'Internal' },
  { id: 'DOC-100243', name: 'Work Order WO/PWD/PUNE/2025/0781', category: 'Work Order', projectId: 'NIR-PWD-2026-0142', uploadedOn: '2025-09-12', uploadedBy: 'EE Office, Pune (Rural)', fileSizeKb: 860, version: 1, accessLevel: 'Restricted', signedBy: 'Er. S. D. Kulkarni' },
  { id: 'DOC-100244', name: 'e-Tender Document eNIT/WRD/2026/0093', category: 'Tender Document', projectId: 'NIR-WRD-2026-0089', uploadedOn: '2026-02-01', uploadedBy: 'WRD e-Tender Cell', fileSizeKb: 5120, version: 1, accessLevel: 'Public', expiryDate: '2026-02-25' },
  { id: 'DOC-100245', name: 'Contract Agreement (EPC) — Package C-4', category: 'Contract Agreement', projectId: 'NIR-PWD-2026-0142', uploadedOn: '2025-09-30', uploadedBy: 'Legal Cell, PWD', fileSizeKb: 8900, version: 1, accessLevel: 'Restricted', signedBy: 'ABC Infrastructure Pvt. Ltd.' },
  { id: 'DOC-100246', name: 'Quality Inspection Report QIR-14 — M35 core test', category: 'Inspection Report', projectId: 'NIR-PWD-2026-0142', uploadedOn: '2026-02-09', uploadedBy: 'Quality Lab (NABL Accredited)', fileSizeKb: 1240, version: 1, accessLevel: 'Internal' },
  { id: 'DOC-100247', name: 'Tranche-3 Utilization Certificate — NIR-UID-2026-0311', category: 'Financial Record', projectId: 'NIR-UID-2026-0311', uploadedOn: '2026-02-09', uploadedBy: 'PAO, UDD', fileSizeKb: 320, version: 1, accessLevel: 'Internal' },
  { id: 'DOC-100248', name: 'Drone Orthomosaic — Ch 42+200 to 45+800 (week 06)', category: 'Site Photograph', projectId: 'NIR-PWD-2026-0142', uploadedOn: '2026-02-09', uploadedBy: 'Field Survey Unit', fileSizeKb: 15600, version: 1, accessLevel: 'Internal' },
  { id: 'DOC-100249', name: 'NABL Certificate — Quality Lab 2026', category: 'Inspection Report', uploadedOn: '2026-01-05', uploadedBy: 'Quality Lab', fileSizeKb: 740, version: 1, accessLevel: 'Public', expiryDate: '2026-12-31' },
  { id: 'DOC-100250', name: 'Forest-land Proposal — Nanded feeder corridor', category: 'Administrative Approval', projectId: 'NIR-MED-2025-0455', uploadedOn: '2025-11-12', uploadedBy: 'EE (O&M), Nanded', fileSizeKb: 2100, version: 2, accessLevel: 'Restricted' },
]

/* ---------- Litigation ---------- */
export const LITIGATION: LitigationCase[] = [
  {
    id: 'LIT-2026-014',
    title: 'Writ Petition re: land compensation — Solapur LI Scheme',
    court: 'Bombay High Court, Aurangabad Bench',
    caseNo: 'WP/1247/2026',
    status: 'hearing_scheduled',
    filedOn: '2026-01-06',
    nextHearing: '2026-02-28',
    projectId: 'NIR-WRD-2026-0089',
    claimAmountCr: 4.2,
    counsel: 'Government Pleader, Aurangabad',
    summary: 'Landowners seek revised compensation per 2013 RFCTLARR circular; dept relying on 2017 award rates.',
  },
  {
    id: 'LIT-2026-018',
    title: 'Arbitration — ABC Infrastructure vs PWD (Package C-4 variation)',
    court: 'Arbitral Tribunal (Retd. Justice R. Mohite)',
    caseNo: 'ARB/02/2025',
    status: 'under_review',
    filedOn: '2025-08-19',
    nextHearing: '2026-03-15',
    projectId: 'NIR-PWD-2026-0142',
    contractor: 'ABC Infrastructure Pvt. Ltd.',
    claimAmountCr: 2.4,
    counsel: 'Standing Counsel, PWD',
    summary: 'Claim for extra items beyond EPC scope; tribunal directing statement of claims by March.',
  },
  {
    id: 'LIT-2025-041',
    title: 'Stay application — substation corridor through forest land',
    court: 'National Green Tribunal, West Zone',
    caseNo: 'OA/88/2025',
    status: 'open',
    filedOn: '2025-10-11',
    nextHearing: '2026-02-24',
    projectId: 'NIR-MED-2025-0455',
    claimAmountCr: 0,
    counsel: 'Govt. Counsel (Environment)',
    summary: 'NGT seeking alternative alignment study before forest diversion approval.',
  },
]

/* ---------- Work orders ---------- */
export const WORK_ORDERS: WorkOrder[] = [
  { id: 'WO/PWD/PUNE/2025/0781', projectId: 'NIR-PWD-2026-0142', contractor: 'ABC Infrastructure Pvt. Ltd.', issuedOn: '2025-09-12', valueCr: 52.0, completionPeriodDays: 540, status: 'in_execution', measurementBookNo: 'MB-PUN-C4-2025-118', defectLiabilityMonths: 60 },
  { id: 'WO/WRD/SOL/2025/0322', projectId: 'NIR-WRD-2026-0089', contractor: 'Shivaay Watertech Ltd.', issuedOn: '2025-03-20', valueCr: 962.0, completionPeriodDays: 850, status: 'in_execution', measurementBookNo: 'MB-SOL-LI2-2025-042', defectLiabilityMonths: 60 },
  { id: 'WO/PWD/NGP/2025/0918', projectId: 'NIR-PWD-2026-0205', contractor: 'Kalyani Buildcon', issuedOn: '2025-10-06', valueCr: 64.8, completionPeriodDays: 480, status: 'in_execution', measurementBookNo: 'MB-NGP-SH248-2025-019', defectLiabilityMonths: 60 },
  { id: 'WO/RHD/AMT/2024/0544', projectId: 'NIR-RHD-2025-0930', contractor: 'ABC Infrastructure Pvt. Ltd.', issuedOn: '2024-05-08', valueCr: 36.6, completionPeriodDays: 570, status: 'closed', measurementBookNo: 'MB-AMT-PMGSY3-2024-077', defectLiabilityMonths: 24 },
  { id: 'WO/MED/NDN/2025/0177', projectId: 'NIR-MED-2025-0455', contractor: 'Shivaay Watertech Ltd.', issuedOn: '2025-02-24', valueCr: 27.4, completionPeriodDays: 880, status: 'suspended', measurementBookNo: 'MB-NDN-FED-2025-011', defectLiabilityMonths: 60 },
]

/* ---------- Inspections ---------- */
export const INSPECTIONS: InspectionRecord[] = [
  { id: 'INS-2026-0231', projectId: 'NIR-PWD-2026-0142', inspectedOn: '2026-02-09', inspector: 'Quality Lab (NABL Accredited)', type: 'Quality', findings: 'Core sample at Ch 44+320 returned 38.4 MPa after 28-day curing — above M35 specification.', geoTag: { lat: 18.372, lng: 74.812 }, photosCount: 12, outcome: 'satisfactory' },
  { id: 'INS-2026-0230', projectId: 'NIR-PWD-2026-0142', inspectedOn: '2026-02-09', inspector: 'Drone Survey Unit', type: 'Routine', findings: 'Orthomosaic shows earthwork behind plan between Ch 44+100 and 44+400.', geoTag: { lat: 18.381, lng: 74.825 }, photosCount: 240, outcome: 'observations', correctiveAction: 'Weekly plan reset; notice to contractor u/s 68-C.' },
  { id: 'INS-2026-0229', projectId: 'NIR-PWD-2026-0205', inspectedOn: '2026-02-08', inspector: 'Er. M. P. Joshi (SE, Nagpur)', type: 'Surprise', findings: 'Pile bore-log vs e-MB discrepancy spans 3–4; re-verification with crosshole sonic logging ordered.', geoTag: { lat: 20.99, lng: 78.62 }, photosCount: 31, outcome: 'non_compliance', correctiveAction: 'Third-party verification; payment withheld for disputed entries.' },
  { id: 'INS-2026-0228', projectId: 'NIR-PHED-2026-0117', inspectedOn: '2026-02-07', inspector: 'Er. H. T. More', type: 'Routine', findings: 'ESR-2 chlorination dosing within limits; 214 km pipeline joint inspection 84% complete.', geoTag: { lat: 20.39, lng: 78.13 }, photosCount: 18, outcome: 'satisfactory' },
  { id: 'INS-2026-0227', projectId: 'NIR-WRD-2026-0089', inspectedOn: '2026-02-06', inspector: 'Financial Advisor, WRD', type: 'Financial', findings: 'Tranche utilization 92.4% vs plan; OEM delay documented with supplier letters.', geoTag: { lat: 17.66, lng: 75.91 }, photosCount: 6, outcome: 'observations' },
]

/* ---------- AI Insights (classification distinguishes AI vs verified vs officer) ---------- */
export const AI_INSIGHTS: AiInsight[] = [
  {
    id: 'AI-2026-044',
    area: 'Project Risk',
    title: 'Monsoon exposure risk on Wardha bridge foundations',
    insight: 'If pile work on spans 3–4 continues past 15 Jun 2026, monsoon river levels historically (2019, 2021) force 45–60 day stand-down. A 6-week acceleration window exists in April–May.',
    supportingData: 'Daily rainfall normals (IMD Satellite Hook) · pile production 3.4 piles/week vs 5.2 required · river gauge history 2019–2025.',
    confidencePct: 82,
    confidenceBand: 'high',
    recommendedAction: 'Convene acceleration review with Kalyani Buildcon; pre-approve second piling rig under clause 31.2.',
    relatedProjectIds: ['NIR-PWD-2026-0205'],
    generatedOn: '2026-02-09',
    classification: 'ai_insight',
  },
  {
    id: 'AI-2026-045',
    area: 'Financial',
    title: 'Fund-flow mismatch: WRD demand vs release pipeline',
    insight: 'Demand 21 head shows released ₹ 1,214.0 Cr against allocation ₹ 1,500.0 Cr; three tranche requests queued for Feb exceed un-released balance by ₹ 88.0 Cr unless re-appropriation is processed.',
    supportingData: 'FundFlow FF-2026-002 · PAO release ledger · pending APR-2026-0412 (₹ 88.0 Cr).',
    confidencePct: 91,
    confidenceBand: 'high',
    recommendedAction: 'Flag to Finance Dept for re-appropriation before releasing Tranche 4.',
    relatedProjectIds: ['NIR-WRD-2026-0089'],
    generatedOn: '2026-02-08',
    classification: 'ai_insight',
  },
  {
    id: 'AI-2026-046',
    area: 'Contractor Evaluation',
    title: 'Composite score movement — Kalyani Buildcon',
    insight: 'Score declined 71→64 over two quarters driven by milestone slippage (41 days) and defect backlog (6 open). Trends suggest further decline if SH-248 pile issue remains open past Mar 2026.',
    supportingData: 'Inspection INS-2026-0229 · defect register · last 4 quarter scorecards.',
    confidencePct: 74,
    confidenceBand: 'medium',
    recommendedAction: 'Attach conditions to any future award pending third-party pile verification.',
    relatedProjectIds: ['NIR-PWD-2026-0205'],
    generatedOn: '2026-02-07',
    classification: 'ai_insight',
  },
  {
    id: 'AI-2026-047',
    area: 'Grievances',
    title: 'Repeat grievance cluster — Pune haul road',
    insight: '5 of last 12 grievances on Package C-4 mention the same haul-road segment (Ch 43+800–44+200). Addressing dust and ponding there could cut repeat complaints ~40%.',
    supportingData: 'GRV-MH-9942, GRV-MH-9918 + 3 related · spray-log · rain days.',
    confidencePct: 68,
    confidenceBand: 'medium',
    recommendedAction: 'Direct contractor to bituminize the 400 m haul segment under safety & environment head.',
    relatedProjectIds: ['NIR-PWD-2026-0142'],
    generatedOn: '2026-02-06',
    classification: 'ai_insight',
  },
]

/* ---------- Citizen-facing summaries (public-safe projection) ---------- */
export const CITIZEN_PROJECTS: CitizenProjectSummary[] = PROJECTS.filter((p) => p.status !== 'on_hold').map((p) => ({
  id: p.id,
  name: p.name,
  department: p.department,
  district: p.district,
  status: p.status,
  sanctionedAmountCr: p.sanctionedAmountCr,
  physicalProgressPct: p.physicalProgressPct,
  expectedCompletion: p.expectedCompletion,
  contractor: p.contractor ?? 'To be appointed',
  scope: p.summary,
  publicMilestones: p.milestones.map((m) => ({ title: m.title, status: m.status, plannedEnd: m.plannedEnd })),
}))

/** Approximate geo-coordinates for "nearby" (demo; district centroid level). */
export const CITIZEN_GEO: Record<string, { lat: number; lng: number }> = {
  Pune: { lat: 18.52, lng: 73.86 },
  Solapur: { lat: 17.66, lng: 75.91 },
  Nashik: { lat: 19.99, lng: 73.79 },
  Wardha: { lat: 20.74, lng: 78.6 },
  Yavatmal: { lat: 20.39, lng: 78.13 },
  Amravati: { lat: 20.93, lng: 77.75 },
  Aurangabad: { lat: 19.88, lng: 75.34 },
  Nanded: { lat: 19.15, lng: 77.32 },
}
