-- Historical version 046 contained hard-coded development organizations and
-- E2E records. Those fixtures must not be installed by a production schema
-- migration. Keep this version as an explicit no-op for migration ordering.
-- Tests create isolated fixtures inside rollback-only transactions instead.
